[package]
name = "editor"
version = "0.1.0"
authors = ["James Mclaughlin <sc19jm2@leeds.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
chrono = "*"
